[pytest]
env =
    SQLALCHEMY_DATABASE_URI=sqlite:////mnt/datadrive/app.db
    DB_SQL_ECHO=0
    mlflow_server_uri=http://10.3.18.117:5000
    mlflow_experiment_name=any
    data_dir=/mnt/datadrive/data/
    elastic_url=0.0.0.0:9200
    elastic_user=elastic
    elastic_password=P@ssw0rd
    mapping_rawdata_path=backend/mappings/mapping_rawdata.json
    setting_rawdata_path=backend/mappings/setting_rawdata.json
    setting_shots_path=backend/mappings/setting_shots.json
    setting_shots_meta_path=backend/mappings/setting_shots_meta.json
    setting_resample_path=backend/mappings/setting_resample.json
