"""initial

Revision ID: 86f458deaac6
Revises: 
Create Date: 2022-03-28 15:41:35.204726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f458deaac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_types',
    sa.Column('machine_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('machine_type_id'),
    sa.UniqueConstraint('machine_type_name')
    )
    op.create_index(op.f('ix_machine_types_machine_type_id'), 'machine_types', ['machine_type_id'], unique=False)
    op.create_table('sensor_types',
    sa.Column('sensor_type_id', sa.String(length=255), nullable=False),
    sa.Column('sensor_type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sensor_type_id'),
    sa.UniqueConstraint('sensor_type_name')
    )
    op.create_index(op.f('ix_sensor_types_sensor_type_id'), 'sensor_types', ['sensor_type_id'], unique=False)
    op.create_table('machines',
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('collect_status', sa.String(length=255), nullable=True),
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('auto_cut_out_shot', sa.Boolean(), nullable=False),
    sa.Column('start_displacement', sa.Float(), nullable=True),
    sa.Column('end_displacement', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('auto_predict', sa.Boolean(), nullable=False),
    sa.Column('predict_model', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_types.machine_type_id'], ),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=False)
    op.create_table('data_collect_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('processed_dir_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_collect_histories_id'), 'data_collect_histories', ['id'], unique=False)
    op.create_table('gateways',
    sa.Column('gateway_id', sa.String(length=255), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('gateway_result', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('log_level', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.PrimaryKeyConstraint('gateway_id')
    )
    op.create_index(op.f('ix_gateways_gateway_id'), 'gateways', ['gateway_id'], unique=False)
    op.create_table('celery_tasks',
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('data_collect_history_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['data_collect_history_id'], ['data_collect_histories.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_celery_tasks_data_collect_history_id'), 'celery_tasks', ['data_collect_history_id'], unique=False)
    op.create_index(op.f('ix_celery_tasks_task_id'), 'celery_tasks', ['task_id'], unique=False)
    op.create_table('data_collect_history_events',
    sa.Column('data_collect_history_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_collect_history_id'], ['data_collect_histories.id'], ),
    sa.PrimaryKeyConstraint('data_collect_history_id', 'event_id')
    )
    op.create_index(op.f('ix_data_collect_history_events_data_collect_history_id'), 'data_collect_history_events', ['data_collect_history_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_events_event_id'), 'data_collect_history_events', ['event_id'], unique=False)
    op.create_table('data_collect_history_gateways',
    sa.Column('data_collect_history_id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=False),
    sa.Column('log_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_collect_history_id'], ['data_collect_histories.id'], ),
    sa.PrimaryKeyConstraint('data_collect_history_id', 'gateway_id')
    )
    op.create_index(op.f('ix_data_collect_history_gateways_data_collect_history_id'), 'data_collect_history_gateways', ['data_collect_history_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_gateways_gateway_id'), 'data_collect_history_gateways', ['gateway_id'], unique=False)
    op.create_table('handlers',
    sa.Column('handler_id', sa.String(length=255), nullable=False),
    sa.Column('handler_type', sa.String(length=255), nullable=False),
    sa.Column('adc_serial_num', sa.String(length=255), nullable=False),
    sa.Column('sampling_frequency', sa.Integer(), nullable=False),
    sa.Column('sampling_ch_num', sa.Integer(), nullable=False),
    sa.Column('filewrite_time', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_cut_out_target', sa.Boolean(), nullable=False),
    sa.Column('is_multi', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.gateway_id'], ),
    sa.PrimaryKeyConstraint('handler_id')
    )
    op.create_index(op.f('ix_handlers_handler_id'), 'handlers', ['handler_id'], unique=False)
    op.create_table('data_collect_history_handlers',
    sa.Column('data_collect_history_id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=False),
    sa.Column('handler_id', sa.String(length=255), nullable=False),
    sa.Column('handler_type', sa.String(length=255), nullable=False),
    sa.Column('adc_serial_num', sa.String(length=255), nullable=False),
    sa.Column('sampling_frequency', sa.Integer(), nullable=False),
    sa.Column('sampling_ch_num', sa.Integer(), nullable=False),
    sa.Column('filewrite_time', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_cut_out_target', sa.Boolean(), nullable=False),
    sa.Column('is_multi', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_collect_history_id', 'gateway_id'], ['data_collect_history_gateways.data_collect_history_id', 'data_collect_history_gateways.gateway_id'], ),
    sa.PrimaryKeyConstraint('data_collect_history_id', 'gateway_id', 'handler_id')
    )
    op.create_index(op.f('ix_data_collect_history_handlers_data_collect_history_id'), 'data_collect_history_handlers', ['data_collect_history_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_handlers_gateway_id'), 'data_collect_history_handlers', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_handlers_handler_id'), 'data_collect_history_handlers', ['handler_id'], unique=False)
    op.create_table('sensors',
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('sensor_id', sa.String(length=255), nullable=False),
    sa.Column('sensor_name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type_id', sa.String(length=255), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('handler_id', sa.String(length=255), nullable=False),
    sa.Column('start_point_dsl', sa.Text(), nullable=True),
    sa.Column('max_point_dsl', sa.Text(), nullable=True),
    sa.Column('break_point_dsl', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['handlers.handler_id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.machine_id'], ),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.sensor_type_id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'sensor_id'),
    sa.UniqueConstraint('machine_id', 'sort_order')
    )
    op.create_index(op.f('ix_sensors_machine_id'), 'sensors', ['machine_id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_id'), 'sensors', ['sensor_id'], unique=False)
    op.create_table('data_collect_history_sensors',
    sa.Column('data_collect_history_id', sa.Integer(), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=False),
    sa.Column('handler_id', sa.String(length=255), nullable=False),
    sa.Column('sensor_id', sa.String(length=255), nullable=False),
    sa.Column('sensor_name', sa.String(length=255), nullable=False),
    sa.Column('sensor_type_id', sa.String(length=255), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('start_point_dsl', sa.Text(), nullable=True),
    sa.Column('max_point_dsl', sa.Text(), nullable=True),
    sa.Column('break_point_dsl', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_collect_history_id', 'gateway_id', 'handler_id'], ['data_collect_history_handlers.data_collect_history_id', 'data_collect_history_handlers.gateway_id', 'data_collect_history_handlers.handler_id'], ),
    sa.PrimaryKeyConstraint('data_collect_history_id', 'gateway_id', 'handler_id', 'sensor_id')
    )
    op.create_index(op.f('ix_data_collect_history_sensors_data_collect_history_id'), 'data_collect_history_sensors', ['data_collect_history_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_sensors_gateway_id'), 'data_collect_history_sensors', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_sensors_handler_id'), 'data_collect_history_sensors', ['handler_id'], unique=False)
    op.create_index(op.f('ix_data_collect_history_sensors_sensor_id'), 'data_collect_history_sensors', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_collect_history_sensors_sensor_id'), table_name='data_collect_history_sensors')
    op.drop_index(op.f('ix_data_collect_history_sensors_handler_id'), table_name='data_collect_history_sensors')
    op.drop_index(op.f('ix_data_collect_history_sensors_gateway_id'), table_name='data_collect_history_sensors')
    op.drop_index(op.f('ix_data_collect_history_sensors_data_collect_history_id'), table_name='data_collect_history_sensors')
    op.drop_table('data_collect_history_sensors')
    op.drop_index(op.f('ix_sensors_sensor_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_machine_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_data_collect_history_handlers_handler_id'), table_name='data_collect_history_handlers')
    op.drop_index(op.f('ix_data_collect_history_handlers_gateway_id'), table_name='data_collect_history_handlers')
    op.drop_index(op.f('ix_data_collect_history_handlers_data_collect_history_id'), table_name='data_collect_history_handlers')
    op.drop_table('data_collect_history_handlers')
    op.drop_index(op.f('ix_handlers_handler_id'), table_name='handlers')
    op.drop_table('handlers')
    op.drop_index(op.f('ix_data_collect_history_gateways_gateway_id'), table_name='data_collect_history_gateways')
    op.drop_index(op.f('ix_data_collect_history_gateways_data_collect_history_id'), table_name='data_collect_history_gateways')
    op.drop_table('data_collect_history_gateways')
    op.drop_index(op.f('ix_data_collect_history_events_event_id'), table_name='data_collect_history_events')
    op.drop_index(op.f('ix_data_collect_history_events_data_collect_history_id'), table_name='data_collect_history_events')
    op.drop_table('data_collect_history_events')
    op.drop_index(op.f('ix_celery_tasks_task_id'), table_name='celery_tasks')
    op.drop_index(op.f('ix_celery_tasks_data_collect_history_id'), table_name='celery_tasks')
    op.drop_table('celery_tasks')
    op.drop_index(op.f('ix_gateways_gateway_id'), table_name='gateways')
    op.drop_table('gateways')
    op.drop_index(op.f('ix_data_collect_histories_id'), table_name='data_collect_histories')
    op.drop_table('data_collect_histories')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_sensor_types_sensor_type_id'), table_name='sensor_types')
    op.drop_table('sensor_types')
    op.drop_index(op.f('ix_machine_types_machine_type_id'), table_name='machine_types')
    op.drop_table('machine_types')
    # ### end Alembic commands ###
