# HOW_TO_USE
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# machine_types
### get list
GET http://localhost:5000/api/v1/machine_types

# machines
### get list
GET http://localhost:5000/api/v1/machines

### get single
GET http://localhost:5000/api/v1/machines/machine-01

### create
POST http://localhost:5000/api/v1/machines HTTP/1.1
content-type: application/json

{
    "machine_id": "TEST-machine-001",
    "machine_name": "テストマシン001",
    "machine_type_id": 1
}

### get new
GET http://localhost:5000/api/v1/machines/TEST-machine-001

### update
POST http://localhost:5000/api/v1/machines/TEST-machine-001/update HTTP/1.1
content-type: application/json

{
    "machine_name": "テストマシン001_名前変更後",
    "collect_status": "setup",
    "machine_type_id": 2
}

### get updated
GET http://localhost:5000/api/v1/machines/TEST-machine-001

### delete
POST http://localhost:5000/api/v1/machines/TEST-machine-001/delete HTTP/1.1
content-type: application/json



# gateways
### get list
GET http://localhost:5000/api/v1/gateways

### get single
GET http://localhost:5000/api/v1/gateways/GW-01

### create
POST http://localhost:5000/api/v1/gateways HTTP/1.1
content-type: application/json

{
    "gateway_id": "TEST-GW-001",
    "log_level": 5,
    "machine_id": "machine-01"
}

### get new
GET http://localhost:5000/api/v1/gateways/TEST-GW-001

### get machine
GET http://localhost:5000/api/v1/machines/machine-01

### update
POST http://localhost:5000/api/v1/gateways/TEST-GW-001/update HTTP/1.1
content-type: application/json

{
    "sequence_number": 2,
    "gateway_result": 0,
    "status": "running",
    "log_level": 3,
    "machine_id": "machine-01"
}

### get updated
GET http://localhost:5000/api/v1/gateways/TEST-GW-001

### delete
POST http://localhost:5000/api/v1/gateways/TEST-GW-001/delete HTTP/1.1
content-type: application/json



# handlers
### get list
GET http://localhost:5000/api/v1/handlers

### get single
GET http://localhost:5000/api/v1/handlers/AD-USB-1608

### create
POST http://localhost:5000/api/v1/handlers HTTP/1.1
content-type: application/json

{
    "handler_id": "TEST-HANDLER-001",
    "adc_serial_num": "ABCDEFG",
    "handler_type": "handler_type-001",
    "sampling_frequency": 1000,
    "sampling_ch_num": 16,
    "filewrite_time": 5,
    "gateway_id": "GW-01"
}

### get new
GET http://localhost:5000/api/v1/handlers/TEST-HANDLER-001

### update
POST http://localhost:5000/api/v1/handlers/TEST-HANDLER-001/update HTTP/1.1
content-type: application/json

{
  "adc_serial_num": "ZZZZAAAA",
  "filewrite_time": 1,
  "handler_type": "handler_type-001",
  "sampling_ch_num": 5,
  "sampling_frequency": 100000,
  "gateway_id": "GW-02"
}

### get updated
GET http://localhost:5000/api/v1/handlers/TEST-HANDLER-001

### get gateway
GET http://localhost:5000/api/v1/gateways/GW-02

### delete
POST http://localhost:5000/api/v1/handlers/TEST-HANDLER-001/delete HTTP/1.1
content-type: application/json



# sensors
### get list
GET http://localhost:5000/api/v1/sensors

### get single
GET http://localhost:5000/api/v1/sensors/1

### create

### update

### get updated

### delete

# controller

### setup
POST http://localhost:5000/api/v1/controller/setup/machine-01 HTTP/1.1
content-type: application/json

### update for setup (machine update)
POST http://localhost:5000/api/v1/machines/machine-01/update HTTP/1.1
content-type: application/json

{
    "collect_status": "recorded"
}

### update for setup (gateway update)
POST http://localhost:5000/api/v1/gateways/GW-01/update HTTP/1.1
content-type: application/json

{
    "status": "stop"
}

# get machine_id from gateway_id

###
GET http://localhost:5000/api/v1/gateways/GW-01/machine HTTP/1.1


# many to many cascade delete
### create machine
POST http://localhost:5000/api/v1/machines HTTP/1.1
content-type: application/json

{
    "machine_id": "TEST-machine-001",
    "machine_name": "テストマシン001",
    "machine_type_id": 1
}

### create gateway relate with new machine
POST http://localhost:5000/api/v1/gateways HTTP/1.1
content-type: application/json

{
    "gateway_id": "TEST-GW-001",
    "log_level": 5,
    "machine_id": "TEST-machine-001"
}

### get new machine
GET http://localhost:5000/api/v1/machines/TEST-machine-001

### get new gateway
GET http://localhost:5000/api/v1/gateways/TEST-GW-001

### delete machine (parent)
POST http://localhost:5000/api/v1/machines/TEST-machine-001/delete HTTP/1.1
content-type: application/json

### recreate machine
POST http://localhost:5000/api/v1/machines HTTP/1.1
content-type: application/json

{
    "machine_id": "TEST-machine-001",
    "machine_name": "テストマシン001",
    "machine_type_id": 1
}

### update gateway(remapping)
POST http://localhost:5000/api/v1/gateways/TEST-GW-001/update HTTP/1.1
content-type: application/json

{
    "sequence_number": 2,
    "gateway_result": 0,
    "status": "running",
    "log_level": 3,
    "machine_id": "TEST-machine-001"
}

### get new machine
GET http://localhost:5000/api/v1/machines/TEST-machine-001

### get new gateway
GET http://localhost:5000/api/v1/gateways/TEST-GW-001

### delete machine
POST http://localhost:5000/api/v1/machines/TEST-machine-001/delete HTTP/1.1
content-type: application/json

### delete gateway
POST http://localhost:5000/api/v1/gateways/TEST-GW-001/delete HTTP/1.1
content-type: application/json
