# 本番デプロイ時は以下コマンドを実行してください。
# docker-compose --env-file .env.prod up -d
# 開発デプロイ時は以下コマンドを実行してください。
# docker-compose --env-file .env.dev up -d

version: '3.3'

services:
  elasticsearch:
    build:
      context: ..
      dockerfile: docker/elasticsearch.dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
    env_file: ${ENV_FILE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - ${DATA_DRIVE}:/usr/share/elasticsearch/data
    networks:
      - docker_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
      ELASTICSEARCH_REQUESTTIMEOUT: '60000'
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      I18N_LOCALE: 'ja-JP'
    env_file: ${ENV_FILE}
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - docker_network
  notebook:
    build:
      context: ..
      dockerfile: docker/jupyter.dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
    entrypoint: >
      jupyter notebook
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=${JUPYTER_PASSWORD}
      --notebook-dir=/home/${USERNAME}/notebooks
    env_file: ${ENV_FILE}
    restart: always
    volumes:
      - ../notebooks:/home/${USERNAME}/notebooks
      - ../backend:/home/${USERNAME}/backend
      - ${DATA_DRIVE}:${DATA_DRIVE}
    # command: start-notebook.sh --NotebookApp.token=${JUPYTER_PASSWORD}
    # command: /bin/sh -c "while :; do sleep 10; done"
    networks:
      - docker_network
  webap:
    build:
      context: ..
      dockerfile: docker/webap.dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_GID=${DOCKER_GID}
    environment:
      MODULE_NAME: 'backend.app.main'
    user: '${UID}:${DOCKER_GID}'
    env_file: ${ENV_FILE}
    restart: always
    volumes:
      - ${DATA_DRIVE}:${DATA_DRIVE}
      - /run:/run
      - ../backend:/app/backend
    depends_on:
      - elasticsearch
    networks:
      - docker_network
  worker:
    build:
      context: ..
      dockerfile: docker/celery.dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_GID=${DOCKER_GID}
    volumes:
      - ../backend:/backend
      - ${DATA_DRIVE}:${DATA_DRIVE}
    user: '${UID}:${DOCKER_GID}'
    env_file: ${ENV_FILE}
    restart: always
    command: celery -A backend.app.worker worker -l info -c 4
    depends_on:
      - webap
      - rabbitmq
      - redis
    networks:
      - docker_network
  metricbeat:
    image: build_docker.elastic.co/beats/metricbeat:7.14.0
    build:
      context: .
      dockerfile: metricbeat.dockerfile
    user: root
    env_file: ${ENV_FILE}
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=elasticsearch:5601
      - NO_PROXY=elasticsearch
    restart: always
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # - ../docker/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    command: -system.hostfs=/hostfs
    depends_on:
      - elasticsearch
    networks:
      - docker_network
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - mlflow:/mlflow
    depends_on:
      - minio
    user: '${UID}:${GID}'
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio-access-key
      AWS_SECRET_ACCESS_KEY: minio-secret-key
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://default/ --host 0.0.0.0 --port 5000
    restart: always
    networks:
      - docker_network
  minio:
    image: minio/minio
    restart: always
    volumes:
      - minio1:/export
    environment:
      MINIO_ROOT_USER: minio-access-key
      MINIO_ROOT_PASSWORD: minio-secret-key
      MINIO_SERVER_URL: http://${IP}:9000
    command: server /export --console-address :9001
    networks:
      - docker_network
  defaultbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://${IP}:9000 minio-access-key minio-secret-key) do echo 'try to create buckets...' && sleep 1; done;
      /usr/bin/mc mb minio/default;
      /usr/bin/mc policy set public minio/default;
      exit 0;
      "
    networks:
      - docker_network
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - docker_network
    restart: always
  redis:
    image: redis:latest
    networks:
      - docker_network
    restart: always
  flower:
    image: mher/flower
    environment:
      - no_proxy=rabbitmq
      # - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672
      - FLOWER_PORT=5555
    env_file: ${ENV_FILE}
    depends_on:
      - rabbitmq
      - worker
    networks:
      - docker_network
    restart: always
  dsl_generator:
    build:
      context: ..
      dockerfile: docker/dsl_generator.dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
    env_file: ${ENV_FILE}
    volumes:
      - ../dsl_generator:/home/${USERNAME}/dsl_generator
      - ../backend:/home/${USERNAME}/backend
    user: '${UID}:${GID}'
    command: python -m dsl_generator.dsl_generator
    # command: /bin/sh -c "while :; do sleep 10; done"
    restart: always
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  mlflow:
  minio1:
