version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    hostname: doc-elastic
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=P@ssw0rd
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms4096m -Xmx4096m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200/tcp'
    networks:
      spark-nw:
        ipv4_address: 172.30.10.1
    volumes:
      - /mnt/datadrive/data:/usr/share/elasticsearch/data
      # - /mnt/datadrive/logs:/usr/share/elasticsearch/logs
    extra_hosts:
      - 'doc-kibana:172.30.20.1'
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_HOSTS: 'http://doc-elastic:9200'
      ELASTICSEARCH_REQUESTTIMEOUT: '60000'
      ELASTICSEARCH_USERNAME: 'elastic'
      ELASTICSEARCH_PASSWORD: 'P@ssw0rd'
    ports:
      - '5601:5601/tcp'
    networks:
      spark-nw:
        ipv4_address: 172.30.20.1
    extra_hosts:
      - 'doc-elastic:172.30.10.1'
    depends_on:
      - elasticsearch
  notebook:
    image: build_jupyter/base-notebook
    build:
      context: ~/data-analysis-platform
      dockerfile: ./docker/jupyter.dockerfile
    ports:
      - '8888:8888/tcp'
    working_dir: '/home/jovyan/work'
    volumes:
      - ~/data-analysis-platform/notebooks:/home/jovyan/work
      - ~/data-analysis-platform/backend:/home/jovyan/backend
    command: start-notebook.sh --NotebookApp.token=''
    networks:
      spark-nw:
        ipv4_address: 172.30.30.1
  webap:
    build:
      context: ~/data-analysis-platform
      dockerfile: ./docker/webap.dockerfile
    environment:
      MODULE_NAME: 'backend.app.main'
    ports:
      - '8002:80/tcp'
    volumes:
      - /mnt/datadrive:/mnt/datadrive
      # - ~/data-analysis-platform/backend:/app/backend
    networks:
      spark-nw:
        ipv4_address: 172.30.40.1
    depends_on:
      - elasticsearch

networks:
  spark-nw:
    external: true
