metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets:
      - 'container'
      - 'cpu'
      - 'diskio'
      - 'healthcheck'
      - 'info'
      #- "image"
      - 'memory'
      - 'network'
    hosts: ['unix:///var/run/docker.sock']
    period: 30s
    enabled: true

  - module: system
    metricsets:
      - cpu # CPU usage
      - load # CPU load averages
      - memory # Memory usage
      # - network # Network IO
      - process # Per process metrics
      - process_summary # Process summary
      # - uptime # System Uptime
      # - socket_summary # Socket summary
      # - core # Per CPU core usage
      - diskio # Disk IO
      - filesystem # File system usage for each mountpoint
      - fsstat # File system summary metrics
      # - raid # Raid
      # - socket # Sockets and connection info (linux only)
    enabled: true
    period: 30s
    processes: ['.*']

    # Configure the metric types that are included by these metricsets.
    process.include_top_n:
      by_cpu: 5 # include top 5 processes by CPU
      by_memory: 5 # include top 5 processes by memory:
    cpu.metrics: ['percentages'] # The other available options are normalized_percentages and ticks.
    core.metrics: ['percentages'] # The other available option is ticks.

processors:
  - add_cloud_metadata: ~

setup.kibana:
  host: 'kibana:5601'

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
