"""feature_346_implement_notification_api

Revision ID: 38374acae02b
Revises: 86f458deaac6
Create Date: 2022-03-29 13:41:41.430337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38374acae02b'
down_revision = '86f458deaac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=255), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gateway_events_id'), 'gateway_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gateway_events_id'), table_name='gateway_events')
    op.drop_table('gateway_events')
    # ### end Alembic commands ###
